---
- name: Show popup message on Windows
  hosts: windows
  gather_facts: no

  tasks:
    - name: Show popup via msg.exe
      ansible.windows.win_shell: |
        msg * "Hello from Semaphore via Ansible!"
